In [ ]:
import os  
curDir = os.getcwd() 
print(curDir)

/root/test folder


In [9]:
import pandas as pd 
df = pd.read_table("/root/kddcup.data",sep=',')  
print df.head(20) 

MemoryError: 

In [3]:
csv_column_names = [
    "duration",
    "protocol_type",
    "service",
    "flag",
    "src_bytes",
    "dst_bytes",
    "land",
    "wrong_fragment",
    "urgent",
    "hot",
    "num_failed_logins",
    "logged_in",
    "num_compromised",
    "root_shell",
    "su_attempted",
    "num_root",
    "num_file_creations",
    "num_shells",
    "num_access_files",
    "num_outbound_cmds",
    "is_host_login",
    "is_guest_login",
    "count",
    "srv_count",
    "serror_rate",
    "srv_serror_rate",
    "rerror_rate",
    "srv_rerror_rate",
    "same_srv_rate",
    "diff_srv_rate",
    "srv_diff_host_rate",
    "dst_host_count",
    "dst_host_srv_count",
    "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate",
    "dst_host_serror_rate",
    "dst_host_srv_serror_rate",
    "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate",
    "category"
]

In [8]:
import pandas as pd
import os
import numpy
datacsv2 = pd.read_csv('kddcup.data.csv', sep=None,names=('A'))
#print("datacsv2:")
#print(type(datacsv2))
print(datacsv2.columns)
a=datacsv2.values[77:88]
print(a)
#",".join(a).split(",")
print(a.split())

Using Python parser to sniff delimiter
Index([u'A'], dtype='object')
[['0,tcp,http,SF,205,1619,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,3,0.00,0.00,0.00,0.00,1.00,0.00,0.00,9,77,1.00,0.00,0.11,0.04,0.00,0.00,0.00,0.00,normal.']
 ['0,tcp,http,SF,207,1583,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,4,4,0.00,0.00,0.00,0.00,1.00,0.00,0.00,10,78,1.00,0.00,0.10,0.04,0.00,0.00,0.00,0.00,normal.']
 ['0,tcp,http,SF,159,4087,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.00,0.00,0.00,0.00,1.00,0.00,0.00,11,79,1.00,0.00,0.09,0.04,0.00,0.00,0.00,0.00,normal.']
 ['0,tcp,http,SF,209,2260,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,6,6,0.00,0.00,0.00,0.00,1.00,0.00,0.00,12,80,1.00,0.00,0.08,0.04,0.00,0.00,0.00,0.00,normal.']
 ['0,tcp,http,SF,206,1619,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,7,7,0.00,0.00,0.00,0.00,1.00,0.00,0.00,13,81,1.00,0.00,0.08,0.04,0.00,0.00,0.00,0.00,normal.']
 ['0,tcp,http,SF,229,21195,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0.00,0.00,0.00,0.00,1.00,0.00,0.00,1,82,1.00,0.00,1.00,0.05,0.00,0.00,0.00,0.00,normal.']
 ['0,tcp,http,

AttributeError: 'numpy.ndarray' object has no attribute 'split'

In [7]:
import numpy as np
from sklearn import datasets
mnist = datasets.fetch_mldata('MNIST original',data_home='.')
n = len(mnist.data)
N = 10000
indices = np.random.permutation(range(n))[:N]
X = mnist.data[indices]
y= mnist.target[indices]
Y = np.eye(10)[y.astype(int)]
print(Y)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


In [13]:
import notebook
print(notebook.__version__)

4.2.1


In [10]:
import pandas as pd
import os
import numpy
datacsv2 = pd.read_csv('/root/kddcup_data_10_percent_corrected.csv')
#print("datacsv2:")
#print(type(datacsv2))
print(datacsv2.columns)
a=datacsv2.values[77:88]
print(a[1:3,0:42])
#",".join(a).split(",")
#print(a.split())

Index([u'duration', u'protocol_type', u'service', u'flag', u'src_bytes', u'dst_bytes', u'land', u'wrong_fragment', u'urgent', u'hot', u'num_failed_logins', u'logged_in', u'num_compromised', u'root_shell', u'su_attempted', u'num_root', u'num_file_creations', u'num_shells', u'num_access_files', u'num_outbound_cmds', u'is_host_login', u'is_guest_login', u'count', u'srv_count', u'serror_rate', u'srv_serror_rate', u'rerror_rate', u'srv_rerror_rate', u'same_srv_rate', u'diff_srv_rate', u'srv_diff_host_rate', u'dst_host_count', u'dst_host_srv_count', u'dst_host_same_srv_rate', u'dst_host_diff_srv_rate', u'dst_host_same_src_port_rate', u'dst_host_srv_diff_host_rate', u'dst_host_serror_rate', u'dst_host_srv_serror_rate', u'dst_host_rerror_rate', u'dst_host_srv_rerror_rate', u'class_label'], dtype='object')
[[0 'tcp' 'http' 'SF' 213 2164 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 15 34 0.0
  0.0 0.0 0.0 1.0 0.0 0.12 211 255 1.0 0.0 0.0 0.01 0.0 0.0 0.0 0.0
  'normal.']
 [0 'tcp' 'http' 'SF' 297 2000 0 0 0 